"""init

Revision ID: 12d71e45ef88
Revises: 
Create Date: 2024-04-28 01:14:37.706559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d71e45ef88'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('active', sa.Integer(), server_default='0', nullable=False),
    sa.Column('car_info', sa.String(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('num_trips', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pasaenger')
    sa.Column('id', sa.Integer(), nullable=False)
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False)
    sa.Column('title', sa.String(), nullable=False)
    sa.Column('stars', sa.Integer(), nullable=False)
    sa.Column('num_trips', sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
